---
kind: pipeline
name: Better Logging CI/CD

steps:
  - name: Generate Script Test
    pull: always
    image: python:3.7-slim
    commands:
      - cd _etc
      - python3 generate-events.py 100

  - name: Backend Tests
    pull: always
    image: python:3.7-slim
    commands:
      - cd backend
      - pip3 install poetry
      - poetry install
      - poetry run pytest

  - name: Frontend Tests
    pull: always
    image: node:13-alpine
    commands:
      - cd frontend
      - npm install
