---
kind: pipeline
name: Better Logging CI/CD

steps:
  - name: Generate Script Test
    pull: always
    image: python:3.6-slim
    commands:
      - cd _etc
      - python3 generate-events.py 100

  - name: Tests
    pull: always
    image: python:3.6-slim
    commands:
      - cp -f README.md backend
      - cd backend
      - pip3 install poetry
      - poetry install
      - poetry run pytest

  - name: Build frontend
    pull: always
    image: node:13-alpine
    commands:
      - cd frontend
      - npm install
      - npm run build

  - name: Build backend
    pull: always
    image: python:3.6-slim
    commands:
      - cd backend
      - pip3 install poetry
      - cp -rf ../frontend/dist/* src/better_logging/static
      - poetry build

  - name: Publish
    pull: always
    image: python:3.6-slim
    failure: ignore
    environment:
      TOKEN:
        from_secret: PYPI_TOKEN
    commands:
      - cp -f README.md backend
      - cd backend
      - pip3 install poetry
      - poetry publish --username __token__ --password $TOKEN
