version: '3'
services:
  db:
    image: postgres
    container_name: better_logging_db
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.sql:/docker-entrypoint-initdb.d/init.sql:ro
  #            - ./tmp/postgres:/var/lib/postgresql/data
