POST http://127.0.0.1:8000/api/search
Content-Type: application/json

{
    "levels": [
        "ERROR",
        "WARN",
        "INFO"
    ],
    "datetime": [
        "2020-02-17",
        "2020-02-18"
    ],
    "modules": [
        "app1",
        "app2"
    ],
    "query": ""
}

###

GET http://127.0.0.1:8080/api/search


###

GET http://127.0.0.1:8000/api/modules

###
